name: jti_adit_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dio_cache_interceptor: ^3.5.0
  dio_cookie_manager: ^3.1.1
  dio: ^5.4.0
  enven: ^0.2.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  get: ^4.6.6
  velocity_x: ^4.1.2
  dropdown_button2: ^2.3.9
  currency_text_input_formatter: ^2.1.13
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

get_cli:
  sub_folder: false
